name: CI

on: [push]
env:
  LAMBDA_NAME: Artidote-Quote

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Build something
      run: make build
    - name: Try to get function
      run: |
        echo ::set-env name=TEST_VARIABLE:: $(aws lambda list-functions --query "Functions[?FunctionName=='${LAMBDA_NAME}'].FunctionName[]" --output text)
    - name: Try to print variable
      run: echo $TEST_VARIABLE
    - name: Do if exist
      if: ${{env.TEST_VARIABLE}} == ${{env.LAMBDA_NAME}}
      run: echo "Exists"
    - name: Do if not exist
      run: echo "Does not exist"
      if: ${{env.TEST_VARIABLE}} == ${{''}}
    - name: Deploy to lambda
      run: |
        aws apigateway get-rest-apis
