name: CI

on: [push]
env:
  LAMBDA_NAME: Artidote-Quot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Build something
      run: make build
    - name: Try to get function
      run: |
        echo ::set-env name=GET_FUNCTION_NAME::$(aws lambda list-functions --query "Functions[?FunctionName=='${LAMBDA_NAME}'].FunctionName[]" --output text)
    - name: Try to print variable
      run: echo $GET_FUNCTION_NAME
    - name: Update function if exist
      run: aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://function.zip
      if: env.GET_FUNCTION_NAME == env.LAMBDA_NAME
    - name: Create Lambda if does not exist
      if: env.GET_FUNCTION_NAME == ''
      run: aws lambda create-function --function-name $LAMBDA_NAME --runtime nodejs10.x --role $AWS_LAMBDA_ROLE --handler index.handler --zip-file fileb://function.zip
